[env:nucleo_g474re]
platform = ststm32
board = nucleo_g474re
framework = arduino
monitor_speed = 115200
; STM32duino usa newlib-nano: printf/snprintf con %f NO imprime el numero
; por defecto. Este flag fuerza al linker a incluir el printf con float
; (en ESP32 %f va de serie; aqui es imprescindible para ver V/T).
build_flags = -Wl,-u,_printf_float
upload_protocol = custom
upload_command = "${platformio.packages_dir}/tool-openocd/bin/openocd.exe" -d1 -s "${platformio.packages_dir}/tool-openocd/openocd/scripts" -f interface/stlink.cfg -c "transport select hla_swd" -f target/stm32g4x.cfg -c "reset_config srst_only srst_nogate connect_assert_srst" -c "program {$PROG_PATH} verify" -c "reset run" -c "shutdown"
